word_list = [
    'Nehal',
    'Sarthak',
    'Abhinav',
    'Saksham',
    'Aryan',
    'Devansh',
    'Tejas',
    'Mohit',
    'Shubam',
    'Mayank',
    'Vijay',
    'Abhay',
    'Manish',
    'Tanisha',
    'Annayna',
    'Anshika',
    'goggle',
    'bookworm',
    'boxcar',
    'boxful',
    'Neha',
    'Anchal',
    'Ravina',
    'buxom',
    'Manthan',
    'buzzing',
    'Harsha',
    'caliph',
    'Aryan',
    'Himanshu',
    'Aman',
    'crypt',
    'Ayush',
    'cycle',
    'Tanmay',
    'Gaurav',
    'Panda',
    'Lion',
    'Shinu',
    'Kaju',
    'Rohit',
    'Amit',
    'Tanu',
    'Diva',
    'Love',
    'heart',
    'Apple',
    'Time',
    # 'fjord',
    # 'flapjack',
    # 'flopping',
    # 'fluffiness',
    # 'flyby',
    # 'foxglove',
    # 'frazzled',
    # 'frizzled',
    # 'fuchsia',
    # 'funny',
    # 'gabby',
    # 'galaxy',
    # 'galvanize',
    # 'gazebo',
    # 'giaour',
    # 'gizmo',
    # 'glowworm',
    # 'glyph',
    # 'gnarly',
    # 'gnostic',
    # 'gossip',
    # 'grogginess',
    # 'haiku',
    # 'haphazard',
    # 'hyphen',
    # 'iatrogenic',
    # 'icebox',
    # 'injury',
    # 'ivory',
    # 'ivy',
    # 'jackpot',
    # 'jaundice',
    # 'jawbreaker',
    # 'jaywalk',
    # 'jazziest',
    # 'jazzy',
    # 'jelly',
    # 'jigsaw',
    # 'jinx',
    # 'jiujitsu',
    # 'jockey',
    # 'jogging',
    # 'joking',
    # 'jovial',
    # 'joyful',
    # 'juicy',
    # 'jukebox',
    # 'jumbo',
    # 'kayak',
    # 'kazoo',
    # 'keyhole',
    # 'khaki',
    # 'kilobyte',
    # 'kiosk',
    # 'kitsch',
    # 'kiwifruit',
    # 'klutz',
    # 'knapsack',
    # 'larynx',
     'lengths',
     'lucky',
     'luxury',
    # 'lymph',
    # 'marquis',
     'matrix',
    # 'megahertz',
    # 'microwave',
    # 'mnemonic',
    # 'mystify',
    # 'naphtha',
     'nightclub',
     'nowadays',
    # 'numbskull',
    # 'nymph',
    # 'onyx',
     'ovary',
     'oxidize',
     'oxygen',
     'pajama',
    # 'peekaboo',
    # 'phlegm',
    'pixel',
     'pizza',
    # 'pneumonia',
    # 'polka',
    # 'pshaw',
    # 'psyche',
     'puppy',
     'puzzle',
    # 'quartz',
     'queue',
     'quips',
    # 'quixotic',
     'quiz',
    # 'quizzes',
    # 'quorum',
    # 'razzmatazz',
    # 'rhubarb',
     'rhythm',
     'rickshaw',
    # 'schnapps',
    # 'scratch',
     'shiv',
    # 'snazzy',
    # 'sphinx',
    # 'spritz',
    # 'squawk',
    # 'staff',
    # 'strength',
    # 'strengths',
    # 'stretch',
    # 'stronghold',
    # 'stymied',
     'subway',
     'swivel',
     'syndrome',
    # 'thriftless',
    # 'thumbscrew',
    # 'topaz',
     'transcript',
    # 'transgress',
     'transplant',
    # 'triphthong',
    # 'twelfth',
    # 'twelfths',
     'unknown',
     'unworthy',
     'unzip',
     'uptown',
    # 'vaporize',
     'vixen',
    # 'vodka',
    # 'voodoo',
    # 'vortex',
    # 'voyeurism',
    # 'walkway',
    # 'waltz',
    'wave',
    'wavy',
    'waxy',
    # 'wellspring',
    # 'wheezy',
    # 'whiskey',
    # 'whizzing',
    # 'whomever',
     'simple',
    'wizard',
    'woozy',
    'Platinum',
    'GOLd',
    'Watch',
    'yippee',
    'Bad',
    'yummy',
    'Good',
    'zigzag',
    'silver',
    'zipper',
    'zodiac',
    'zombie',
]
